### ISSUE TITLE
Event #1

### ISSUE THREAD

**Issue by iancrowther** [nottsjs/feedback#2]

**Comment by shakyShane** [comment]
Great first event, really enjoyed helping out!

**Comment by mathewtrivett** [comment]
Github issues blow my mind, in a great way!

Great first event, and nice to have the pair programming approach.  Would be great to get a bit of an overviewing of what the value of node.js is and what it's great at maybe at the next time :)

As a new javascript developer.

**Comment by mathewtrivett** [comment]
Didn't quite finish that bit of feedback... I meant to say as a learner getting to grips with JavaScript it felt like a welcoming and supportive meetup.

I wish I'd had a bigger appetite for the great catering.

**Comment by iancrowther** [comment]
Lol thanks @mathewtrivett, see you at the next one.   Your going to mentor right?

**Comment by mathewtrivett** [comment]
@iancrowther definately will be there. Wow, that's very kind but I'm very much a starter learner but I would feel comfortable mentoring around Javascript basics perhaps?  I'm not sure I'd be confident at all as a fully fledged mentor : /

**Comment by iancrowther** [comment]
You were great, no one knows it all.. Plus Google is your friend
