### ISSUE TITLE
Focus channels of communication

### ISSUE THREAD

**Issue by iancrowther** [nottsjs/feedback#6]
At Octobers event, @olizilla raised a fair point that we should focus our communications into less channels.  

As a result, I'm proposing we drop the Gitter and focus on the news letter and twitter to drive discussion to github.

**Comment by joemckie** [comment]
I think gitter can be quite handy for general chat, but it'd definitely be better keeping the important stuff on GitHub, i.e. speaker requests etc...

**Comment by iancrowther** [comment]
We should drive traffic ot github via tweets and use twitter for important links..

keep gitter for chat
