### ISSUE TITLE
Brain Dump

### ISSUE THREAD

**Issue by jackthorley** [nottsjs/feedback#8]
Hey,

Apologies for the brain dump of ideas - I noted them down during my last attendance and forgot to drop them on an issue. I can split them into different feedback issues if you feel the need to discuss them individually.
- When using black presentation make sure to turn the front lights off.
- Having one feedback mechanism is great! Multiple announce, single aggregation.
- Tickets are very off putting for many people, it forms an additional barrier to entry this generally affects 'last minuters' and those who's schedules are more haphazard.
- Sort out the next event prior to the current event so you're able to be more explicit to attendees. I understand this may have been difficult in the beginning, but judging by your speakers repo this might no longer be a problem.

**Comment by iancrowther** [comment]
@jackthorley 
1. noted
2. thanks
3. its kinda necessary tho so we know how much food to order, we just need a rep that walkins are welcome, they must wrestle for food though! :-p
4. We have always got the next event in hand prior, great tip though

Many thanks for your feedback, it really is apreciated and helps us get better.  

if we dont dim the lights, shout up!

**Comment by iancrowther** [comment]
cc' @joemckie @nomad3k @grahamsmith
