### ISSUE TITLE
Make the topic for each talk public.

### ISSUE THREAD

**Issue by jessicabrentnall** [nottsjs/feedback#9]
If you say "this week the talk/workshop will be..." it makes it more appealing (to those who would be interested) and makes it easier to sell "Hey guys, come to NottsJS! Learn some Node an shizz!"

**Comment by iancrowther** [comment]
again - great feedback

**Comment by iancrowther** [comment]
@wordshaker - please see the website refresh.  has your feedback been resolved or do we need more?

**Comment by jessicabrentnall** [comment]
Looks great to me. Cheers!
